spring:
  config:
    activate:
      on-profile: prod
    import: application-secret.properties

jwt:
  jwk:
    issuer: ${MAKERS_AUTH_JWK_ISSUER}

external:
  auth:
    url: https://auth.api.sopt.org
    api-key: ${AUTH_API_KEY}
    service-name: ${OUR_SERVICE_NAME}
    endpoints:
      jwk: ${MAKERS_AUTH_JWK_ENDPOINT}