spring:
  config:
    activate:
      on-profile: dev
    import: application-secret.properties

jwt:
  jwk:
    url: ${DEV_MAKERS_AUTH_JWK_URL}
    key-id: ${MAKERS_AUTH_JWK_KEY_ID}
    issuer: ${MAKERS_AUTH_JWK_ISSUER}